include(FindPackageHandleStandardArgs)
unset(OPENCV_FOUND)
set(OPENCV-VERSION opencv-4.1.0_cuda-11.1)

# OpenCV头文件查找
find_path(OpenCV_INCLUDE_DIR NAMES opencv2 HINTS ${LIB_PATH}/include/${OPENCV-VERSION}/opencv4 NO_DEFAULT_PATH)

find_library(OPENCV_CORE NAMES libopencv_core.so PATHS ${LIB_PATH}/lib/${OPENCV-VERSION} NO_DEFAULT_PATH)
find_library(OPENCV_HIGHGUI NAMES libopencv_highgui.so PATHS ${LIB_PATH}/lib/${OPENCV-VERSION} NO_DEFAULT_PATH)
find_library(OPENCV_IMGPROC NAMES libopencv_imgproc.so PATHS ${LIB_PATH}/lib/${OPENCV-VERSION} NO_DEFAULT_PATH)
find_library(OPENCV_IMGCODECS NAMES libopencv_imgcodecs.so PATHS ${LIB_PATH}/lib/${OPENCV-VERSION} NO_DEFAULT_PATH)
find_library(OPENCV_VIDEO NAMES libopencv_video.so PATHS ${LIB_PATH}/lib/${OPENCV-VERSION} NO_DEFAULT_PATH)
find_library(OPENCV_OPTFLOW NAMES libopencv_cudaoptflow.so PATHS ${LIB_PATH}/lib/${OPENCV-VERSION} NO_DEFAULT_PATH)
find_library(OPENCV_CUDAIMGPROC NAMES libopencv_cudaimgproc.so PATHS ${LIB_PATH}/lib/${OPENCV-VERSION} NO_DEFAULT_PATH)
set(OpenCV_LIBRARIES ${OPENCV_CORE} ${OPENCV_HIGHGUI} ${OPENCV_IMGPROC} ${OPENCV_IMGCODECS} ${OPENCV_CUDAIMGPROC} ${OPENCV_OPTFLOW} ${OPENCV_VIDEO})

# 第一个参数即为外部find_package()函数的参数，后面的变量都有效时第一个参数对应的<UPPERCASED_NAME>_FOUND变量被置为true
find_package_handle_standard_args(OpenCV DEFAULT_MSG OPENCV_CORE
                                  OPENCV_HIGHGUI OPENCV_IMGPROC OPENCV_VIDEO
                                  OPENCV_OPTFLOW OPENCV_CUDAIMGPROC OPENCV_IMGCODECS)

# 设置外部使用的变量
if(OPENCV_FOUND)
    set(OpenCV_LIBRARIES ${OPENCV_OPTFLOW} ${OPENCV_VIDEO} ${OPENCV_CORE} ${OPENCV_HIGHGUI} ${OPENCV_IMGPROC} ${OPENCV_IMGCODECS} ${OPENCV_CUDAIMGPROC})
    set(OpenCV_INCLUDE_DIRS ${OpenCV_INCLUDE_DIR})
endif(OPENCV_FOUND)